/**
 * AUTOGENERATED FILE: DO NOT MODIFY
 *
 * This file was auto generated by shadcn.
 */

import { clsx, type ClassValue } from "clsx";
import { twMerge } from "tailwind-merge";

export function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs));
}
