# Trigger on main branch for deployment only
trigger:
  branches:
    include:
      - main

pr:
  branches:
    include:
      - '*'

pool:
  vmImage: ubuntu-latest

jobs:
  - job: Build_and_Test
    displayName: "Build and Test"
    steps:
      - task: Bash@3
        displayName: "Create .env.local file"
        inputs:
          targetType: 'inline'
          script: |
            echo "NEXT_PUBLIC_BASE_URL=$(NEXT_PUBLIC_BASE_URL)" >> .env.local

      - task: NodeTool@0
        inputs:
          versionSpec: "22.3.0"
        displayName: "Install Node.js"

      - script: |
          npm install
          npm run build
        displayName: "npm install and build"

      # Run unit tests using Jest
      - script: |
          npm run test
        displayName: "Run unit tests"

  # Job for deploying to Vercel, runs only after a successful merge to main
  - job: Deploy_to_Vercel
    displayName: "Deploy to Vercel"
    dependsOn: Build_and_Test
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
    steps:
      - task: vercel-deployment-task@1
        inputs:
          vercelProjectId: 'prj_HlYmw1X08BTJXRu51b8twEu5yV7r'
          vercelOrgId: 'LHQkb1ozqXb9n8IPg9u4pM3w'
          vercelToken: $(VERCEL_TOKEN)
          production: true